metadata:
  namespace: dev-test
  name: catlog-service
  labels:
    app: catlog-service
    version: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catlog-service
      version: alpha
  strategy:
    type: Recreate
  template:
    metadata:
      name: catlog-service
      labels:
        app: catlog-service
        version: alpha
    spec:
       containers:
       - name: catlog-service
         image: pathandawood/catlog-service:2
         imagePullPolicy: Always
         ports:
         - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: catlog-service
  namespace: dev-test
  labels:
    app: catlog-service
    version: alpha
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: catlog-service
    version: alpha
